# configuration for "non-master" branches
-
  image: Visual Studio 2017
  branches:
    except:
    - master
  version: 1.0.{build}
  configuration: Release
  platform: Any CPU
  environment:
    COVERALLS_TOKEN:
      secure: yQbjLdQV0mU9QgTmlINi4ey+Y+gGaiz/EZqfr/41adeVjgGc9GhgJA3W/FArFAVu
    NUGET_SOURCE: https://www.myget.org/F/dhgms/api/v2/package
    NUGET_APIKEY:
      secure: RErDVlA5kOT7ZT4maCrp4KE73pzZYaMz5T+OrDqRu2AObjUTaNNvTvRwEqlve/O+
    sonarqubeLogin:
      secure: cn/J1/GsOt4dF7zRxdB9ajSk1/UzxYZq0MMLLQPkFA92GtrWIYeiKgrzC2d5z7bq
  build_script:
    - ps: .\build.ps1
  artifacts:
    - path: artifacts/*.nupkg
    - path: '**/*.binlog'
  test: off
  on_failure:
    - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

# configuration for "master" branch
-
  image: Visual Studio 2017
  branches:
    only:
    - master
  version: 1.0.{build}
  configuration: Release
  platform: Any CPU
  environment:
    COVERALLS_TOKEN:
      secure: yQbjLdQV0mU9QgTmlINi4ey+Y+gGaiz/EZqfr/41adeVjgGc9GhgJA3W/FArFAVu
    GITHUB_USERNAME:
      secure: mHIm6yhC2xu2toMv1z91YA==
    GITHUB_TOKEN:
      secure: 9ULk5oYK+0ELg1yx5HovqzJvKrcAP9JBeE11VFd9svWDLKT7M8BPUsaiosmawiN3
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: 8GpBZ6IHRM4AV4mP8qCqUgJi0NCHX17OlzbrEZRoDCE0s2ZwXHOeqMfIwrGaakg9
    sonarqubeLogin:
      secure: cn/J1/GsOt4dF7zRxdB9ajSk1/UzxYZq0MMLLQPkFA92GtrWIYeiKgrzC2d5z7bq
  build_script:
    - ps: .\build.ps1
  artifacts:
    - path: artifacts/*.nupkg
    - path: '**/*.binlog'
  test: off
  on_failure:
    - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }