name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      solutionpath: src\WsusSmartApprove.sln
      unittestprojectpath: src\WsusSmartApprove.UnitTests\WsusSmartApprove.UnitTests.csproj
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@1982f45c4877fb5ee2ed3a4d01a3fe957ece8bf7
      
    - name: Install RSAT WSUS tools
      run: Install-WindowsFeature UpdateServices-API
      shell: powershell
    - name: Build
      run: .\build.ps1
      shell: powershell
      
# only store binlog on failure      
    - name: store binlogs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: binlogs
        path: artifacts/binlog
        
    - name: store docfx
      if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
      uses: actions/upload-artifact@v2
      with:
        name: docfx
        path: artifacts/docfx
        
    - name: store nuget packages
      if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: artifacts/nuget
        
    - name: store omd
      if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
      uses: actions/upload-artifact@v2
      with:
        name: omd
        path: artifacts/omd
        
    - name: store outdated
      if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
      uses: actions/upload-artifact@v2
      with:
        name: outdated
        path: artifacts/outdated
        
    - name: store snitch
      if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
      uses: actions/upload-artifact@v2
      with:
        name: snitch
        path: artifacts/snitch
